all:
	gcc  powerpc_gcc_500v2.c -o powerpc-linux-gnu-gcc

install:all
	chmod a+x powerpc-linux-gnu-gcc
	cp -f powerpc-linux-gnu-gcc /opt/freescale/usr/local/gcc-4.4.78-eglibc-2.10.78/powerpc-linux-gnu/bin
